version: '3.8'

services:
  cardiovision:
    build:
      context: ../  # Use parent directory as the build context
      dockerfile: DoCker/Dockerfile
    image: tavivision
    ports:
      - "20201:20201"
    volumes:
      - ./TAVIVision:/app
    tty: true
    stdin_open: true
    restart: unless-stopped  # Ensures the container restarts if it crashes
    env_file: .env

